# Generated by Django 2.2.5 on 2019-10-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreiningTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening_topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TreningChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treningChoiceDescribe', models.CharField(max_length=200)),
                ('treningChoiceQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_page.TreiningTopic')),
            ],
        ),
    ]
