# Generated by Django 2.2.7 on 2019-11-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treningchoice',
            name='treningChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='TreiningTopic',
        ),
        migrations.DeleteModel(
            name='TreningChoice',
        ),
    ]
