# Generated by Django 2.2.7 on 2019-11-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingquestion',
            old_name='question_text',
            new_name='training_title',
        ),
    ]
